//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSP.inc.cs.CustomExtenders.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_PlaceSearch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_PlaceSearch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSP.inc.cs.CustomExtenders.Properties.Resources.PlaceSearch", typeof(Resources_PlaceSearch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference name=&quot;MicrosoftAjax.js&quot;/&gt;
        ///
        ///(function () {
        ///    Type.registerNamespace(&quot;Sys&quot;);
        ///    Type.registerNamespace(&quot;Sys.Extended&quot;);
        ///    Type.registerNamespace(&quot;Sys.Extended.UI&quot;);
        ///
        ///    var scriptName = &quot;LocationPlaceSearch&quot;;
        ///
        ///    function execute() {
        ///
        ///        Sys.Extended.UI.LocationPlaceSearch = function (element) {
        ///            Sys.Extended.UI.LocationPlaceSearch.initializeBase(this, [element]);
        ///
        ///            this._LocationIconControlID = &quot;&quot;;
        ///            this._DetailsControlID = &quot;&quot;;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LocationPlaceSearchBehavior {
            get {
                return ResourceManager.GetString("LocationPlaceSearchBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;reference name=&quot;MicrosoftAjax.js&quot;/&gt;
        ///
        ///(function () {
        ///    // debug
        ///    Type.registerNamespace(&quot;Sys&quot;);
        ///    Type.registerNamespace(&quot;Sys.Extended&quot;);
        ///    Type.registerNamespace(&quot;Sys.Extended.UI&quot;);
        ///
        ///    var scriptName = &quot;LocationPlaceSearch&quot;;
        ///
        ///    if (Type._registerScript) {
        ///        Type._registerScript(&quot;LocationPlaceSearchBehavior.js&quot;);
        ///    }
        ///
        ///    function execute() {
        ///
        ///        Sys.Extended.UI.LocationPlaceSearch = function (element) {
        ///            Sys.Extended.UI.LocationPlaceSearch.initializ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LocationPlaceSearchBehavior_debug {
            get {
                return ResourceManager.GetString("LocationPlaceSearchBehavior_debug", resourceCulture);
            }
        }
    }
}
